config/routes.rb
BookSelf::Application.routes.draw do

  resources :authors do
    resources :books
  end

  resources :orders
  resources :categories

  root :to => 'authors#index'

end

app/models/address.rb
class Address
	
  include Mongoid::Document
  # include Geocoder::Model::Mongoid
  attr_accessible :street, :zip, :city, :state, :country
  field :street, type: String
  field :zip, type: Integer
  field :city, type: String
  field :state, type: String
  field :country, type: String

  field :coordinates, type: Array
  belongs_to :address
  belongs_to :location, polymorphic: true
  # geocoded_by :formatted_addr
  # after_validation :geocode

  # def formatted_addr
  #	[street, city, state, country].join(',')
  # end
end

app/models/author.rb
class Author
  include Mongoid::Document
  field :name, type: String

  validates_presence_of :name

  after_initialize :init_address
  protected
  	def init_address
    	address ||= build_address
	end
  

  has_one :address, as: :location, autosave: true, dependent: :destroy
  has_many :books, autosave: true, dependent: :destroy

  accepts_nested_attributes_for :books, :address, allow_destroy: true
  
end

app/models/book.rb
class Book
  include Mongoid::Document

  field :title, type: String
  field :publisher, type: String
  field :published_on, type: Date
  field :price, localize: true
  field :votes, type: Array

  validates :title, presence: true

  belongs_to :author
  has_and_belongs_to_many :categories

#  embeds_many :reviews
end

app/models/category.rb
class Category
  include Mongoid::Document

  field :name, type: String
  has_and_belongs_to_many :books
end

app/models/lease.rb
class Lease
  include Mongoid::Document

  field :from, type: DateTime
  field :till, type: DateTime

  embedded_in :order
end

app/models/order.rb
class Order
  include Mongoid::Document

  field :created_at, type: DateTime
  field :type, type: String # Lease, Purchase

  belongs_to :book
  belongs_to :member

  embeds_one :lease
  embeds_one :purchase
end

app/models/purchase.rb
class Purchase
  include Mongoid::Document

  field :quantity, type: Integer
  field :price, type: Float

  embedded_in :order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	def index
		@authors = Author.all.includes(:books)
	end 
 
	def new
		@author = Author.new
		@author.build_address
		@author.books.build
	end

	def create
		@author = Author.new(params[:author])
		@author.save!
			redirect_to authors_path, notice: "Author created successfully"
		
		
	end

	def edit
		@author = Author.find(params[:id])
		if @author.update_attributes(params[:author])
			redirect_to authors_path, notice: "Author Updated successfully"
		else
			render :edit
		end		
	end

	def update
		@author = Author.find(params[:id])
		if @author.update_attributes(params[:author])
			redirect_to authors_path, notice: "Author updated successfully"
		else
			render :edit
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/index.html.haml
%h1 All Authors
%table{:class => "table table-striped table-bordered table-condensed"}
	%thead
		%tr
			%th Name
			%th Books
	%tbody
		- @authors.each do |author|
			%tr
				%th= link_to author.name, edit_author_path(author)
				%th= author.books.collect(&:title).to_sentence

app/views/authors/new.html.haml
%h2 New Author
= simple_nested_form_for(@author, :html => {:class => 'well form-horizontal'}) do |f|
	= f.input :name
	= render(:partial => "shared/address", :locals =>{:f =>f} )
	%h2 Books
	= f.fields_for :books do |b|
		%fieldset{:class => 'well'}
			= b.input :title
			= b.input :publisher
			= b.association :categories, collection: Category.all
			= b.link_to_remove "Remove", :class => "btn btn-danger"
	= f.link_to_add "Add Book", :books, :class => "btn btn-success"
	= f.submit :class => 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html{:lang => :en}
	%head
		%meta{:charset => "utf-8"}/
		%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
		%title BookShelf
		= javascript_include_tag "application"
		= stylesheet_link_tag "application"
		= csrf_meta_tags
	%body
		.navbar
			.navbar-inner
				.container-fluid
					= link_to "BookShelf", root_path, :class => 'brand'
					%ul.nav
						%li.dropdown
							%a.dropdown-toggle{ :href => '#', "data-toggle" => "dropdown"}
								="Authors"
								%b.caret
							%ul.dropdown-menu
								%li= link_to "List Authors", authors_path
								%li= link_to "New Author", new_author_path
						%li= link_to "Orders", orders_path
						%li= link_to "New Order", new_order_path
		.container
			.content
				= yield
			.footer
				%p Goldie Kedia &copy; TheOne 2011

app/views/shared/_address.html.haml
= f.fields_for :address do |b|
	= b.input :street
	= b.input :zip
	= b.input :city
	= b.input :state